In [2]:
import numpy as np

In [3]:
# creating one dimensional array
arr = np.array([1,2,3,4,5])
print(arr)

# elements of an array can be accessed through index
# index of an array starts with 0

print(arr[3])

[1 2 3 4 5]
4


In [4]:
# creating 2d arrayzoho_o_insert_call
lis1 = [1,2,3,4,5,6]
lis2 = [7,8,9,10,11,12]
lis3 = [13,14,15,16,17,18]
arr2d = np.array([lis1,lis2,lis3])
print(arr2d)

# we can check the shape of array by shape function
print(arr2d.shape)

# we can reshape an array by reshape function, but the number of element should be smae
print(arr2d.reshape(2,9))

# As it is a 2d array we can access the elements in the following way
print(arr2d[1][1])
print(arr2d[:3,2:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]
8
[[ 3  4]
 [ 9 10]
 [15 16]]


In [5]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3d)
print(arr3d[1][1][2])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
6


In [6]:
# we can create and check dimensions of an array using ndmin and ndim respectively
print(arr2d.ndim)
print(arr3d.ndim)
arr5d = np.array([1,2,3,4,5],ndmin=5)
print(arr5d)
print(arr5d.ndim)

2
3
[[[[[1 2 3 4 5]]]]]
5


In [7]:
# we can check array data type
print(arr2d.dtype)

int32


In [16]:
str_lis = [1,23,3,4,1]
str_arr = np.array(str_lis,dtype="S")
str_arr

array([b'1', b'23', b'3', b'4', b'1'], dtype='|S2')

In [29]:
# conert array to different data type using astype('data type')
flt_arr = np.array([1.1,23.2,3.3,4.1,1.0])
flt_arr
int_arr = flt_arr.astype('i')
int_arr
print(flt_arr.dtype)
print(int_arr.dtype)

float64
int32


In [32]:
# itering through array using nditer()

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [33]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [34]:
# joining array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


In [37]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [42]:
# spliting array
arr = np.array([[1, 2, 3], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18]])]


In [43]:
# performs binary search
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [45]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [47]:
# generate a sequence of elements for array using arange
a = np.arange(1,19)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])