In [1]:
import pandas as pd
import numpy as np

In [2]:
# create dataframe using np array
df = pd.DataFrame(np.arange(0,10).reshape(2,5),index=["row1","row2"],columns=["column1","column2","column3","column4","column5"])
df

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9

In [3]:
a = [1, 7, 2]
myvar = pd.DataFrame(a,index=["x","y","z"])
myvar

0
x  1
y  7
z  2

In [4]:
# Accessing elements in pandas
# loc is used to access a specific row or rows
# dataframe.loc[rowname]
df.loc["row1"]

column1    0
column2    1
column3    2
column4    3
column5    4
Name: row1, dtype: int32

In [5]:
df.loc[["row1","row2"]]

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9

In [6]:
# Accessing elements using iloc
df.iloc[0,2]

2

In [7]:
# Turn dataframe to array using values function
df.iloc[:,:].values

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
df.loc["row1"].values

array([0, 1, 2, 3, 4])

In [9]:
df['column1']

row1    0
row2    5
Name: column1, dtype: int32

In [10]:
df[['column1','column2']]

column1  column2
row1        0        1
row2        5        6

In [11]:
# check null values in the dataframe
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
column5    0
dtype: int64

In [12]:
df.value_counts()

column1  column2  column3  column4  column5
0        1        2        3        4          1
5        6        7        8        9          1
dtype: int64

In [13]:
df['column1'].unique()

array([0, 5])

In [14]:
test_csv = pd.read_csv("test.csv")
test_csv.tail()

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[5 rows x 378 columns]

In [15]:
test_csv.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [16]:
test_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [17]:
test_csv["ID"].value_counts()

0       1
5600    1
5604    1
5606    1
5611    1
       ..
2788    1
2790    1
2791    1
2793    1
8417    1
Name: ID, Length: 4209, dtype: int64

In [18]:
test_csv.loc[4208].value_counts()

0         313
1          55
8417        1
110.85      1
z           1
r           1
ae          1
c           1
d           1
aa          1
g           1
w           1
Name: 4208, dtype: int64

In [19]:
# get only specific columns
# test_csv[['ID','y']]
test_specific_col_csv = pd.read_csv("test.csv",usecols=['ID','y'])
test_specific_col_csv

ID       y
0        0  130.81
1        6   88.53
2        7   76.26
3        9   80.62
4       13   78.02
...    ...     ...
4204  8405  107.39
4205  8406  108.77
4206  8412  109.22
4207  8415   87.48
4208  8417  110.85

[4209 rows x 2 columns]

In [20]:
test_csv.dtypes

ID        int64
y       float64
X0       object
X1       object
X2       object
         ...   
X380      int64
X382      int64
X383      int64
X384      int64
X385      int64
Length: 378, dtype: object

In [46]:
# read html
mal_url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
anime_table = pd.read_html(mal_url)


In [47]:
anime_table[0]

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[4]  
3  Internal use in private networks, no roaming[4]

In [48]:
anime_table[1]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [49]:
# read html
mal_url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
anime_table = pd.read_html(mal_url,header=0)

In [50]:
anime_table[0]

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[4]  
3  Internal use in private networks, no roaming[4]

In [51]:
anime_table[1]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]